apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test
  #namespace: demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-wan