apiVersion: v1
kind: Service
metadata:
  name: {{ include "arkid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "arkid.name" . }}
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webServer.port }}
      targetPort: 80
      protocol: TCP
      name: http
    # - name: ldap
    #   port: {{ .Values.service.ldap.ldapPort }}
    #   targetPort: 389
    #   protocol: TCP
    # - name: ldaps
    #   port: {{ .Values.service.ldap.ldapsPort }}
    #   targetPort: 636
    #   protocol: TCP
    - name: broker
      port: {{ .Values.service.webServerBroker.port }}
      targetPort: 8080
      protocol: TCP
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    - name: ldap
      port: 389
      protocol: TCP
      targetPort: 389

  selector:
    app.kubernetes.io/name: {{ include "arkid.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
