apiVersion: v1
kind: ReplicationController
metadata:
  name: account
  labels:
    name: account
spec:
  replicas: 1   #副本数为3，k8s会自动进行负载均衡
  selector:
    name: account
  template:
    metadata:
      name: account
      labels:
        name: account
    spec:
      containers:
      - name: account
        image: nginx  #刚上传至私有仓库的镜像
        imagePullPolicy: IfNotPresent    #镜像拉取策略
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  type: NodePort
  selector:
    name: account
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
